SELECT 
		a.ID
		, id_carga
		, a.FACTURA
		, a.PRESTADOR
		--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
		--, a.EPS, a.TIPO_USUARIO
		, a.TIPO_IDENTIFICACION
		, a.ID_PERSONA
		, a.EDAD
		, a.SEXO
		, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
		, a.FECHA_CONSULTA, a.AUTORIZACION
		, a.COD_CONSULTA AS servicio
		, COALESCE(s1.DESCRIPCION,s2.descripcion) AS servicio_desc
		, s1.SECCION AS servicio_seccion
		, s1.CAPITULO_DESC AS servicio_capitulo
		, cast(TRY_CAST(a.FINALIDAD_CONSULTA AS double) AS int) AS finalidad
		, cast(TRY_CAST(a.CAUSA_EXTERNA AS double) AS int) AS causa_externa
		, a.DX_PPAL as dx
		, d1.DIAGNOSTICO_DESC AS DX_DESC, d1.CIE10_3DIG_DESC AS DX_3DIG_DESC, d1.CAPITULO AS DX_CAPITULO
		, a.DX_REL1
		, d2.DIAGNOSTICO_DESC AS DX_REL1_DESC, d2.CIE10_3DIG_DESC AS DX_REL1_3DIG_DESC, d2.CAPITULO AS DX_REL1_CAPITULO
		, a.DX_REL2
		, d3.DIAGNOSTICO_DESC AS DX_REL2_DESC, d3.CIE10_3DIG_DESC AS DX_REL2_3DIG_DESC, d3.CAPITULO AS DX_REL2_CAPITULO
		, a.DX_REL3
		, d4.DIAGNOSTICO_DESC AS DX_REL3_DESC, d4.CIE10_3DIG_DESC AS DX_REL3_3DIG_DESC, d4.CAPITULO AS DX_REL3_CAPITULO
		, a.TIPO_DX_PPAL
		, a.VALOR_CONSULTA
		, a.VALOR_CUOTA_MODERADORA
		, a.VALOR_NETO_PAGAR
		--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
	FROM VP_INFORMACION.OUTLIERS.RIPS_AC a
		LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d1 ON a.DX_PPAL=d1.DIAGNOSTICO
		LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d2 ON a.DX_REL1=d2.DIAGNOSTICO 
		LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d3 ON a.DX_REL2=d3.DIAGNOSTICO 
		LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d4 ON a.DX_REL3=d4.DIAGNOSTICO 
		LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_PROCEDIMIENTOS s1 ON a.COD_CONSULTA=s1.CODIGO AND YEAR(a.FECHA_CONSULTA)=s1.VIGENCIA
		LEFT JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY codigo ORDER BY  vigencia DESC) AS orden, * FROM VP_INFORMACION.OUTLIERS.REFERENCIAS_PROCEDIMIENTOS) s2 ON s1.CODIGO IS NULL AND s2.orden=1 AND a.COD_CONSULTA=s2.CODIGO