SELECT 
	a.ID
	, id_carga
	, a.FACTURA
	, a.PRESTADOR
	--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
	--, a.EPS, a.TIPO_USUARIO
	, a.TIPO_IDENTIFICACION
	, a.ID_PERSONA
	, a.EDAD
	, a.SEXO
	, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
	, a.AUTORIZACION
	, a.VIA_INGRESO 
	, a.FECHA_INGRESO
	, a.CAUSA_EXTERNA  
	, a.DX_PPAL_INGRESO AS DX_INGRESO  
	, d1.DIAGNOSTICO_DESC AS DX_INGRESO_DESC, d2.CIE10_3DIG_DESC AS DX_INGRESO_3DIG_DESC, d2.CAPITULO AS DX_INGRESO_CAPITULO
	, a.FECHA_EGRESO
	, a.DX_PPAL_EGRESO AS DX_EGRESO
	, d2.DIAGNOSTICO_DESC AS DX_EGRESO_DESC, d2.CIE10_3DIG_DESC AS DX_EGRESO_3DIG_DESC, d2.CAPITULO AS DX_EGRESO_CAPITULO
	, a.DX1_EGRESO 
	, d3.DIAGNOSTICO_DESC AS DX_REL1_EG_DESC, d3.CIE10_3DIG_DESC AS DX_REL1_EG_3DIG_DESC, d3.CAPITULO AS DX_REL1_EG_CAPITULO
	, a.DX2_EGRESO  
	, d4.DIAGNOSTICO_DESC AS DX_REL2_EG_DESC, d4.CIE10_3DIG_DESC AS DX_REL2_EG_3DIG_DESC, d4.CAPITULO AS DX_REL2_EG_CAPITULO
	, a.DX3_EGRESO  
	, d5.DIAGNOSTICO_DESC AS DX_REL3_EG_DESC, d5.CIE10_3DIG_DESC AS DX_REL3_EG_3DIG_DESC, d5.CAPITULO AS DX_REL3_EG_CAPITULO
	, a.DX_COMPLICACION  
	, d6.DIAGNOSTICO_DESC AS DX_COMP_DESC, d6.CIE10_3DIG_DESC AS DX_COMP_3DIG_DESC, d6.CAPITULO AS DX_COMP_CAPITULO
	, a.ESTADO_SALIDA  
	, a.CAUSA_BASICA_MUERTE 
	, d7.DIAGNOSTICO_DESC AS DX_MUERTE_DESC, d7.CIE10_3DIG_DESC AS DX_MUERTE_3DIG_DESC, d7.CAPITULO AS DX_MUERTE_CAPITULO
	--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
FROM VP_INFORMACION.OUTLIERS.RIPS_Ah a
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d1 ON a.DX_PPAL_INGRESO=d1.DIAGNOSTICO
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d2 ON a.DX_PPAL_EGRESO=d2.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d3 ON a.DX1_EGRESO=d3.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d4 ON a.DX2_EGRESO=d4.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d5 ON a.DX3_EGRESO=d5.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d6 ON a.DX_COMPLICACION=d6.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d7 ON a.CAUSA_BASICA_MUERTE=d7.DIAGNOSTICO