SELECT 
	a.ID
	, id_carga
	, a.FACTURA
	, a.PRESTADOR
	--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
	--, a.EPS, a.TIPO_USUARIO
	, a.TIPO_IDENTIFICACION
	, a.ID_PERSONA
	, a.EDAD
	, a.SEXO
	, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
	, a.AUTORIZACION
	, a.COD_MEDICAMENTO, a.TIPO_MEDICAMENTO, a.NOMBRE_GENERICO, a.FORMA_FARMACEUTICA
	, a.CONCENTRACION_MEDICAMENTO AS concentracion
	, a.UNIDAD_MEDIDA
	, a.NUM_UNIDADES AS cantidad
	, a.VALOR_UNITARIO_MEDICAMENTO AS valor_unitario
	, a.VALOR_TOTAL_MEDICAMENTO AS valor_total
	--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
FROM VP_INFORMACION.OUTLIERS.RIPS_Am a