SELECT 
	a.ID
	, id_carga
	, a.FACTURA
	, a.PRESTADOR
	--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
	--, a.EPS, a.TIPO_USUARIO
	, a.TIPO_IDENTIFICACION
	, a.ID_PERSONA
	, a.EDAD
	, a.SEXO
	, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
	, a.FECHA_NACIMIENTO 
	, TRY_CAST(a.EDAD_GESTACIONAL AS double) AS edad_gestacional
	, a.SEXO_RN 
	, a.PESO_RN 
	, a.DX
	, d1.DIAGNOSTICO_DESC AS DX_DESC, d2.CIE10_3DIG_DESC AS DX_3DIG_DESC, d2.CAPITULO AS DX_CAPITULO
	, a.CAUSA_BASICA_MUERTE
	, d2.DIAGNOSTICO_DESC AS DX_MUERTE_DESC, d2.CIE10_3DIG_DESC AS DX_MUERTE_3DIG_DESC, d2.CAPITULO AS DX_MUERTE_CAPITULO
	, a.FECHA_MUERTE 
	--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
FROM VP_INFORMACION.OUTLIERS.RIPS_An a
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d1 ON a.DX=d1.DIAGNOSTICO
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d2 ON a.CAUSA_BASICA_MUERTE=d2.DIAGNOSTICO