SELECT 
	a.ID
	, id_carga
	, a.FACTURA
	, a.PRESTADOR
	--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
	--, a.EPS, a.TIPO_USUARIO
	, a.TIPO_IDENTIFICACION
	, a.ID_PERSONA
	, a.EDAD
	, a.SEXO
	, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
	, a.fecha_procedimiento AS fecha
	, a.AUTORIZACION
	, a.COD_PROCEDIMIENTO AS servicio
	, COALESCE(s1.DESCRIPCION,s2.descripcion) AS servicio_desc
	, s1.SECCION AS servicio_seccion
	, s1.CAPITULO_DESC AS servicio_capitulo
	, a.AMBITO_PROCEDIMIENTO AS ambito
	, a.PERSONA_ATIENDE AS persona_que_atiende
	, a.FINALIDAD_PROCEDIMIENTO AS finalidad
	, a.DX_PPAL
	, d1.DIAGNOSTICO_DESC AS DX_PPAL_DESC, d1.CIE10_3DIG_DESC AS DX_PPAL_3DIG_DESC, d1.CAPITULO AS DX_PPAL_CAPITULO
	, a.DX_REL
	, d2.DIAGNOSTICO_DESC AS DX_REL_DESC, d2.CIE10_3DIG_DESC AS DX_REL_3DIG_DESC, d2.CAPITULO AS DX_REL_CAPITULO
	, a.DX_COMPLICACION 
	, d3.DIAGNOSTICO_DESC AS DX_COMPLICACION_DESC, d3.CIE10_3DIG_DESC AS DX_COMPLICACION_3DIG_DESC, d3.CAPITULO AS DX_COMPLICACION_CAPITULO
	, a.FORMA_REALIZACION_ACTOQX AS forma_realizacion_atrqx
	, a.VALOR_PROCEDIMIENTO AS valor
	--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
FROM VP_INFORMACION.OUTLIERS.RIPS_Ap a
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d1 ON a.DX_PPAL=d1.DIAGNOSTICO
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d2 ON a.DX_REL=d2.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d3 ON a.DX_COMPLICACION=d3.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_PROCEDIMIENTOS s1 ON a.COD_PROCEDIMIENTO=s1.CODIGO AND YEAR(a.FECHA_PROCEDIMIENTO)=s1.VIGENCIA
	LEFT JOIN (SELECT ROW_NUMBER() OVER(PARTITION BY codigo ORDER BY  vigencia DESC) AS orden, * FROM VP_INFORMACION.OUTLIERS.REFERENCIAS_PROCEDIMIENTOS) s2 ON s1.CODIGO IS NULL AND s2.orden=1 AND a.COD_PROCEDIMIENTO=s2.CODIGO