SELECT 
	a.ID
	, id_carga
	, a.FACTURA
	, a.PRESTADOR
	--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
	--, a.EPS, a.TIPO_USUARIO
	, a.TIPO_IDENTIFICACION
	, a.ID_PERSONA
	, a.EDAD
	, a.SEXO
	, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
	, a.AUTORIZACION
	, a.TIPO_SERVICIO 
	, a.COD_SERVICIO AS servicio
	, a.NOM_SERVICIO AS servicio_desc
	, a.CANTIDAD 
	, a.VALOR_UNITARIO 
	, a.VALOR_TOTAL 
	--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
FROM VP_INFORMACION.OUTLIERS.RIPS_At a