SELECT 
	a.ID
	, id_carga
	, a.FACTURA
	, a.PRESTADOR
	--, a.FECHA_EXP_FACTURA, a.FECHA_INICIO, a.FECHA_FIN, a.REGIMEN, a.VALOR_TOTAL_FACTURA
	--, a.EPS, a.TIPO_USUARIO
	, a.TIPO_IDENTIFICACION
	, a.ID_PERSONA
	, a.EDAD
	, a.SEXO
	, a.DIVIPOLA, a.DEPARTAMENTO, a.MUNICIPIO, a.ZONA
	, a.FECHA_INGRESO
	, a.FECHA_SALIDA 
	, a.AUTORIZACION
	, a.DX_SALIDA 
	, d1.DIAGNOSTICO_DESC AS DX_SALIDA_DESC, d2.CIE10_3DIG_DESC AS DX_SALIDA_3DIG_DESC, d2.CAPITULO AS DX_SALIDA_CAPITULO
	, a.DX_REL1
	, d2.DIAGNOSTICO_DESC AS DX_REL1_DESC, d2.CIE10_3DIG_DESC AS DX_REL1_3DIG_DESC, d2.CAPITULO AS DX_REL1_CAPITULO
	, a.DX_REL2
	, d3.DIAGNOSTICO_DESC AS DX_REL2_DESC, d3.CIE10_3DIG_DESC AS DX_REL2_3DIG_DESC, d3.CAPITULO AS DX_REL2_CAPITULO
	, a.DX_REL3
	, d4.DIAGNOSTICO_DESC AS DX_REL3_DESC, d4.CIE10_3DIG_DESC AS DX_REL3_3DIG_DESC, d4.CAPITULO AS DX_REL3_CAPITULO
	, a.DESTINO_SALIDA 
	, a.ESTADO_SALIDA
	, a.CAUSA_BASICA_MUERTE 
	, d5.DIAGNOSTICO_DESC AS DX_MUERTE_DESC, d5.CIE10_3DIG_DESC AS DX_MUERTE_3DIG_DESC, d5.CAPITULO AS DX_MUERTE_CAPITULO
	--, a.FECHA_CREACION_TABLA, a.FILENAME, a.FECHA_REGISTRO_SNOWFLAKE, a.NUM_POS_FILE
FROM VP_INFORMACION.OUTLIERS.RIPS_Au a
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d1 ON a.DX_SALIDA=d1.DIAGNOSTICO
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d2 ON a.DX_REL1=d2.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d3 ON a.DX_REL2=d3.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d4 ON a.DX_REL3=d4.DIAGNOSTICO 
	LEFT JOIN VP_INFORMACION.OUTLIERS.REFERENCIAS_DIAGNOSTICO d5 ON a.CAUSA_BASICA_MUERTE=d5.DIAGNOSTICO