SELECT
	u.ID
	, u.FUENTE
	, u.id_carga
	, u._ID_PERSONA AS id_persona
	, u.TIPO_IDENTIFICACION
	--, u.NUMERO_IDENTIFICACION
	, u._EPS AS eps
	--, u.CODENTADMIN
	, try_cast(u.TIPO_USUARIO AS integer) AS TIPO_USUARIO
	, u.EDAD
	, u.SEXO
	, u.DIVIPOLA, u.DEPARTAMENTO, u.MUNICIPIO, u.ZONA_RESIDENCIAL
	--, u.FECHA_CREACION_TABLA, u.FILENAME, u.FECHA_REGISTRO_SNOWFLAKE, u.NUM_POS_FILE
--SELECT DISTINCT TIPO_USUARIO, TRY_CAST(TIPO_USUARIO AS double)
FROM VP_INFORMACION.OUTLIERS.RIPS_US u