SELECT
    f.PRESTADOR,
    f.FACTURA,
    f.ID_CARGA,
    f.FECHA_EXP_FACTURA,
    f.FECHA_INICIO,
    f.FECHA_FIN,
    f.REGIMEN,
    f.CONTRATO,
    f.VALOR_TOTAL_COPAGO,
    f.VALOR_COMISION,
    f.VALOR_DESCUENTOS,
    f.VALOR_NETO,
FROM VP_INFORMACION.OUTLIERS.RIPS_AF__ANON f