SELECT
    PRESTADOR,
    ID_CARGA,
    FACTURA,
    count(*) AS registros,
    count(DISTINCT id_persona) AS personas_unicas,
    count(DISTINCT iff(sexo='F',id_persona,NULL)) AS mujeres,
    count(DISTINCT iff(edad<18,id_persona,NULL)) AS menores,
    avg(edad) AS edad_avg,
    stddev(edad) AS edad_std,
    approx_percentile(edad,0.5) AS edad_p50,
    count(iff(sexo='F',id_persona,NULL)) AS atenciones_a_mujeres,
    count(iff(edad<18,id_persona,NULL)) AS atenciones_a_menores,
    count(iff(zona='R',ID_PERSONA,NULL)) AS atenciones_a_rurales,
    count(DISTINCT DEPARTAMENTO) AS departamentos,
    count(DISTINCT divipola) AS ciudades,
    --
    count(DISTINCT cod_medicamento) AS medicamentos, 
    count(DISTINCT iff(tipo_medicamento=2,cod_medicamento,NULL)) AS medicamentos_nopbs,
    -- pbs
    sum(iff(tipo_medicamento=1,cantidad,NULL)) AS pbs_und_sum,
    avg(iff(tipo_medicamento=1,cantidad,NULL)) AS pbs_und_avg,
    stddev(iff(tipo_medicamento=1,cantidad,NULL)) AS pbs_und_std,
    APPROX_PERCENTILE(iff(tipo_medicamento=1,cantidad,NULL), 0.5) AS pbs_und_p50,
    sum(iff(tipo_medicamento=1,valor_total,NULL)) AS pbs_valor_sum,
    avg(iff(tipo_medicamento=1,valor_unitario,NULL)) AS pbs_valor_avg,
    stddev(iff(tipo_medicamento=1,valor_unitario,NULL)) AS pbs_valor_std,
    approx_percentile(iff(tipo_medicamento=1,valor_unitario,NULL),0.5) AS pbs_valor_p50,
    -- nopbs
    sum(iff(tipo_medicamento=2,cantidad,NULL)) AS nopbs_und_sum,
    avg(iff(tipo_medicamento=2,cantidad,NULL)) AS nopbs_und_avg,
    stddev(iff(tipo_medicamento=2,cantidad,NULL)) AS nopbs_und_std,
    APPROX_PERCENTILE(iff(tipo_medicamento=2,cantidad,NULL), 0.5) AS nopbs_und_p50,
    sum(iff(tipo_medicamento=2,valor_total,NULL)) AS nopbs_valor_sum,
    avg(iff(tipo_medicamento=2,valor_unitario,NULL)) AS nopbs_valor_avg,
    stddev(iff(tipo_medicamento=2,valor_unitario,NULL)) AS nopbs_valor_std,
    approx_percentile(iff(tipo_medicamento=2,valor_unitario,NULL),0.5) AS nopbs_valor_p50,
FROM VP_INFORMACION.OUTLIERS.RIPS_Am__ANON 
GROUP BY ALL